"""Auto migration

Revision ID: 591f29f5d6a6
Revises: 1187d146f87f
Create Date: 2026-02-17 17:54:17.822154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591f29f5d6a6'
down_revision = '1187d146f87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
